### ISSUE TITLE
shit is so broken

### ISSUE THREAD

**Issue by rethinkingrn** [RandoNandoz/RandoNandoz.github.io#3]
**### 

- [x] why does clicking on the site give me popup
![xdxdxdxd](https://user-images.githubusercontent.com/48839277/54860606-d532c800-4cd9-11e9-99bb-a1d9a8e91373.png)

**

**Comment by RandoNandoz** [comment]
change the <script> values you n-word

**Comment by RandoNandoz** [comment]
<b>nigga<b/>
